<a href="https://colab.research.google.com/github/himanshisangani64-beep/numpy_all_code/blob/main/Basic_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Task 1.1: Basic Filtering

In [2]:
ages = np.array([25, 30, 18, 35, 22, 40, 17])
ages

array([25, 30, 18, 35, 22, 40, 17])

In [18]:
adutls  = np.array([ages > 30])
adutls

array([[False, False, False,  True, False,  True, False]])

Task 1.2: Filtering with Multiple Conditions

In [28]:
young_adults = ages[(ages > 20) & (ages < 35)]
young_adults

array([25, 30, 22])

Task 1.3: Filtering Strings

In [29]:
name = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve'])
name

array(['Alice', 'Bob', 'Charlie', 'David', 'Eve'], dtype='<U7')

In [51]:
n = (np.char.startswith(name,'A')) | (np.char.startswith(name,'E'))
name[n]


array(['Alice', 'Eve'], dtype='<U7')

Task 2.1: Basic Masking for Selection

In [76]:
temperatures = np.array([28, 32, 25, 35, 30, 22, 38])
temperatures

array([28, 32, 25, 35, 30, 22, 38])

In [77]:
is_not = temperatures >30
is_not

array([False,  True, False,  True, False, False,  True])

In [78]:
hot_Temperature = temperatures[is_not]
hot_Temperature

array([32, 35, 38])

Task 2.2: Masking for Modification

In [89]:
for i in range(len(hot_Temperature)):
  hot_Temperature[i]=31

In [91]:
print("Change Celsius 30 Degree above is set  31 Celsius ",hot_Temperature)

Change Celsius 30 Degree above is set  31 Celsius  [31 31 31]


Task 2.3: Using np.where() for Masking

In [92]:
scores = np.array([65, 80, 72, 90, 55, 78])
scores

array([65, 80, 72, 90, 55, 78])

In [97]:
grades = np.where(scores > 75,"Pass","Fail")
grades

array(['Fail', 'Pass', 'Fail', 'Pass', 'Fail', 'Pass'], dtype='<U4')


Task 3.1: Reshaping a 1D array to 2D

In [100]:
numbers_1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
numbers_2d = numbers_1d.reshape(3,4)

In [101]:
numbers_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Task 3.2: Reshaping a 2D array to 1D (Flattening)

In [102]:
numbers_2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Task 3.3: Reshaping with -1

In [103]:
values = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [105]:
values.reshape(5,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

Task 4.1: Broadcasting a Scalar to an Array

In [106]:
price = np.array([10,20,30,40])
price

array([10, 20, 30, 40])

In [107]:
price +5

array([15, 25, 35, 45])

Task 4.2: Broadcasting a 1D Array to a 2D Array (Row-wise)

In [108]:
sales = np.array([[10,20],[15,25],[12,18]])
sales

array([[10, 20],
       [15, 25],
       [12, 18]])

In [123]:
sales.shape

(3, 2)

In [125]:
bonuses = np.array([[[1],[2],[3]],[[1],[1],[1]]])
bonuses

array([[[1],
        [2],
        [3]],

       [[1],
        [1],
        [1]]])

In [126]:
bonuses.shape

(2, 3, 1)

In [127]:
add_bonuses = sales + bonuses
add_bonuses

array([[[11, 21],
        [17, 27],
        [15, 21]],

       [[11, 21],
        [16, 26],
        [13, 19]]])

Task 4.3: Broadcasting a 1D Array to a 2D Array (Column-wise)

In [129]:
tax_rates = np.array([0.1, 0.05])
tax_rates

array([0.1 , 0.05])

In [131]:
add_tax = sales * tax_rates
add_tax

array([[1.  , 1.  ],
       [1.5 , 1.25],
       [1.2 , 0.9 ]])