<a href="https://colab.research.google.com/github/himanshisangani64-beep/numpy_all_code/blob/main/demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Libray

In [ ]:
import numpy as np

Print Version

In [ ]:
np.__version__

'2.0.2'

One Dimensional Array

In [ ]:
arr = np.array([i for i in range(0,10)])
arr1 = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Tow Dimensonal Array With Shape Ane DataType

In [ ]:
a2 = np.array([[4,6,2],[5,4,6]])

In [ ]:
a2

array([[4, 6, 2],
       [5, 4, 6]])

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2.dtype

dtype('int64')

50 Evenly spaced value between 0 and 10

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

List V/s Array

In [ ]:
l1 = [1,2,3,4,5]
l1 + [10]        # List In Addtion

[1, 2, 3, 4, 5, 10]

In [ ]:
a = np.array([1,2,3,4,5])
a + [10]      # Array In Addtion

array([11, 12, 13, 14, 15])

Array of All Zero

In [ ]:
z = np.zeros(shape=(3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Array of All Ones

In [ ]:
one = np.ones(shape=(2,5))
one.dtype

dtype('float64')

In [ ]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Array In arange()

In [ ]:
r = np.arange(0,50,5)
r

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

Identity matrix

In [ ]:
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
i.shape

(3, 3)

4 X 4 Array

In [ ]:
ar = np.arange(1,17).reshape(4,4)

In [ ]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Array Indexing And slicing

In [ ]:
a01 = np.arange(1,15,1)
a01[3:9]   # index 3 to 8
           # output  = 3 to 8 index on value

array([4, 5, 6, 7, 8, 9])

In [ ]:
a02 = np.arange(1,10).reshape(3,3)
a02

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

second row third column

In [ ]:
a02[1,2]

np.int64(6)

In [ ]:
a03 = np.arange(1,17).reshape(4,4)
a03

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Last Tow Row And Cloumu

In [ ]:
a03[2:,2:]

array([[11, 12],
       [15, 16]])

5 X 5 Array  In Replace First row 100 value

In [ ]:
a05 = np.array([[11,23,65,88,27],
                [34,50,34,15,34],
                [43,23,12,44,22],
                [44,34,23,35,11],
                [23,25,43,25,32]])
a05

array([[11, 23, 65, 88, 27],
       [34, 50, 34, 15, 34],
       [43, 23, 12, 44, 22],
       [44, 34, 23, 35, 11],
       [23, 25, 43, 25, 32]])

In [ ]:
a05[0:1] = 100

In [ ]:
a05

array([[100, 100, 100, 100, 100],
       [ 34,  50,  34,  15,  34],
       [ 43,  23,  12,  44,  22],
       [ 44,  34,  23,  35,  11],
       [ 23,  25,  43,  25,  32]])

Greater Than 5 with boolean indexing

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])