<a href="https://colab.research.google.com/github/himanshisangani64-beep/numpy_all_code/blob/main/searching_Sorting_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Mathematical Operations

1) Create two NumPy arrays of shape (3, 3) and perform element-wise addition,subtraction, multiplication, and division

In [50]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
addition = a + 10
addition

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [11]:
subtract = a - 5
subtract

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [12]:
multiplication = a * 100
multiplication

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

In [13]:
division  = a / 5
division

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2],
       [1.4, 1.6, 1.8]])

2) Generate a NumPy array with random integers and apply square root, exponential, and logarithmic functions.

In [27]:
a = np.array([np.random.randint(1,20,10)])
a

array([[ 4,  4, 10, 11, 18, 10, 12, 17, 13, 11]])

In [28]:
np.sqrt(a)

array([[2.        , 2.        , 3.16227766, 3.31662479, 4.24264069,
        3.16227766, 3.46410162, 4.12310563, 3.60555128, 3.31662479]])

In [31]:
np.exp(a)

array([[5.45981500e+01, 5.45981500e+01, 2.20264658e+04, 5.98741417e+04,
        6.56599691e+07, 2.20264658e+04, 1.62754791e+05, 2.41549528e+07,
        4.42413392e+05, 5.98741417e+04]])

In [32]:
np.log(a)

array([[1.38629436, 1.38629436, 2.30258509, 2.39789527, 2.89037176,
        2.30258509, 2.48490665, 2.83321334, 2.56494936, 2.39789527]])

In [33]:
np.log10(a)

array([[0.60205999, 0.60205999, 1.        , 1.04139269, 1.25527251,
        1.        , 1.07918125, 1.23044892, 1.11394335, 1.04139269]])

In [34]:
np.log2(a)

array([[2.        , 2.        , 3.32192809, 3.45943162, 4.169925  ,
        3.32192809, 3.5849625 , 4.08746284, 3.70043972, 3.45943162]])

3. Create a NumPy array and apply trigonometric operations like sin, cos, and tan

In [35]:
np.sin(a)

array([[-0.7568025 , -0.7568025 , -0.54402111, -0.99999021, -0.75098725,
        -0.54402111, -0.53657292, -0.96139749,  0.42016704, -0.99999021]])

In [36]:
np.cos(a)

array([[-0.65364362, -0.65364362, -0.83907153,  0.0044257 ,  0.66031671,
        -0.83907153,  0.84385396, -0.27516334,  0.90744678,  0.0044257 ]])

In [37]:
np.tan(a)

array([[   1.15782128,    1.15782128,    0.64836083, -225.95084645,
          -1.13731371,    0.64836083,   -0.63585993,    3.49391565,
           0.46302113, -225.95084645]])

In [38]:
np.cosh(a)

array([[2.73082328e+01, 2.73082328e+01, 1.10132329e+04, 2.99370709e+04,
        3.28299846e+07, 1.10132329e+04, 8.13773957e+04, 1.20774764e+07,
        2.21206696e+05, 2.99370709e+04]])

In [39]:
np.degrees(np.sin(a))

array([[-43.36158891, -43.36158891, -31.17011362, -57.29521839,
        -43.02839971, -31.17011362, -30.7433636 , -55.08401872,
         24.0737979 , -57.29521839]])

4. Normalize a NumPy array using vectorized operations (subtract mean and divide by std).

In [54]:
mean = np.mean(a)
std = np.std(a)
normalize = (a - mean)  / std
normalize

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

5)  Implement a function using NumPy that calculates the Euclidean distance between two points.

In [139]:

def Euclidean_Distance(l,l1):
  return np.sqrt(np.sum((l-l1)**2))


l = np.array([1,6,12])
l1 = np.array([2,4,8])

e1 = Euclidean_Distance(l1,l)
e1

np.float64(4.58257569495584)

. Combining and Splitting Arrays

 1) Create two 1D arrays and concatenate them horizontally and vertically.

In [142]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [151]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

2. Stack multiple 2D arrays using vstack and hstack and then split them back using vsplit and hsplit.

In [152]:
np.vstack([a,b]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [153]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [160]:
np.split(a,1,axis=0)

[array([1, 2, 3])]

In [172]:
np.hsplit(a,1)

[array([1, 2, 3])]

In [173]:
a2 = np.array([[1,2,3,1],[4,5,6,7]])
a2

array([[1, 2, 3, 1],
       [4, 5, 6, 7]])

In [178]:
np.vsplit(a2,2)

[array([[1, 2, 3, 1]]), array([[4, 5, 6, 7]])]

In [179]:
np.hsplit(a2,2)

[array([[1, 2],
        [4, 5]]),
 array([[3, 1],
        [6, 7]])]

 3 . Create a 2D array and split it into 4 equal sub-arrays.

In [183]:
np.split(a2,4,axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]]),
 array([[1],
        [7]])]

4. Demonstrate the difference between concatenate, stack, and hstack functions using 2D arrays.

In [185]:
a3 = np.array([[5,5,4,1],[4,4,3,7]])
np.concatenate([a2,a3],axis=1)

array([[1, 2, 3, 1, 5, 5, 4, 1],
       [4, 5, 6, 7, 4, 4, 3, 7]])

In [186]:
np.stack([a2,a3],axis=1)

array([[[1, 2, 3, 1],
        [5, 5, 4, 1]],

       [[4, 5, 6, 7],
        [4, 4, 3, 7]]])

In [187]:
np.hstack([a2,a3])

array([[1, 2, 3, 1, 5, 5, 4, 1],
       [4, 5, 6, 7, 4, 4, 3, 7]])

In [188]:
np.vstack([a2,a3])

array([[1, 2, 3, 1],
       [4, 5, 6, 7],
       [5, 5, 4, 1],
       [4, 4, 3, 7]])

5. Create a 3D array and flatten it, then reshape it back to its original shape.


In [189]:
a3d = np.array([
    [
        [1,2],
        [3,4],
        [5,6]
    ],

    [   [8,7],
        [9,10],
        [11,12]
    ]])
a3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 8,  7],
        [ 9, 10],
        [11, 12]]])

In [190]:
a3d.shape

(2, 3, 2)

In [191]:
a3d.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  7,  9],
        [10, 11, 12]]])

In [192]:
a3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  8,  7,  9, 10, 11, 12])

. Search, Sort, Aggregating/Statistical Functions

1. Create a NumPy array and find the index of the maximum and minimum elements.

In [214]:
a1d = np.array([1,2,3,4,5])
np.max(a1d)

np.int64(5)

In [217]:
np.where(a1d > 3)

(array([3, 4]),)

In [219]:
np.min(a1d)

np.int64(1)

2. Sort a 2D array along different axes and display the result

In [224]:
a3

array([[5, 5, 4, 1],
       [4, 4, 3, 7]])

In [226]:
np.sort(a3,axis=0)

array([[4, 4, 3, 1],
       [5, 5, 4, 7]])

In [227]:
np.sort(a3,axis=1)

array([[1, 4, 5, 5],
       [3, 4, 4, 7]])

3.Generate a random NumPy array and find the mean, median, variance, and standard deviation.*

In [228]:
np.mean(a2)

np.float64(3.625)

In [229]:
np.std(a2)

np.float64(2.117634293262177)

In [230]:
np.median(a2)

np.float64(3.5)

In [231]:
np.var(a2)

np.float64(4.484375)


4. Use np.where to find all elements greater than a certain threshold in a given array.

In [234]:
a = np.array([1,6,3,8,2,7,3,6,4,8,2,4,1,9,5])
np.where(a > 5)

(array([ 1,  3,  5,  7,  9, 13]),)

5. Create a NumPy array and count how many elements are positive, negative, or zero.

In [238]:
arr_1 = np.array([-2,-3,-1,0,-4,7,2,0])
arr_1[arr_1 == 0].size

2

In [239]:
arr_1[arr_1 > 0].size

2

In [240]:
arr_1[arr_1 < 0].size

4